server:
  port: 8080
  servlet:
    context-path: /

spring:
  thymeleaf:
    cache: false
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  application:
    name: mall
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）
  rabbitmq:
    host: 192.168.120.100 # rabbitmq的连接地址
    port: 5672 # rabbitmq的连接端口号
    virtual-host: /mall # rabbitmq的虚拟host
    username: mall # rabbitmq的用户名
    password: mall # rabbitmq的密码
    listener:
      direct:
        # 确认模式：NONE：使用rabbitmq的自动确认
        # AUTO：使用rabbitmq的手动确认, springboot会自动发送确认回执 (默认)
        # MANUAL：使用rabbitmq的手动确认, 且必须手动执行确认操作
        acknowledge-mode: auto
      simple:
        prefetch: 5 # 抓取数量

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: mall，一个购物商城
  try-host: http://localhost:${server.port}

elasticsearch:
  host: 192.168.120.100
  port: 9200

jwt:
  secret: chao
  expiration: 180
  tokenHeader: _token

mall:
  authcode:
    prefix: _authcode
    expire: 120
